#!/bin/bash
# An installable list of the Atom IDE plugins that I use.
# To get "apm" tool: open Atom and click "Atom->Install Shell Commands"
apm install $(cat<<-EOF
Sublime-Style-Column-Selection
Zen
angularjs
ask-stack
atom-beautify
atom-bootstrap3
atom-cli-diff
atom-color-highlight
atom-html-preview
atom-ternjs
atom-typescript
atomatigit
atomic-rest
autocomplete-emojis
center-screen
change-case
color-picker
copy-as-rtf
coverage
docblockr
editorconfig
fancy-new-file
file-icons
filesize
git-blame
git-control
git-difftool
git-log
git-plus
git-tab-status
go-plus
hex
highlight-cov
highlight-line
highlight-selected
keybinding-cheatsheet
language-jade
language-mumps
language-svg
language-viml
linter
linter-clang
linter-coffeelint
linter-cpplint
linter-csslint
linter-eslint
linter-javac
linter-js-yaml
linter-jscs
linter-jshint
linter-less
linter-pep8
linter-perl
linter-pylint
linter-scss-lint
linter-shellcheck
linter-tslint
linter-write-good
linter-xmllint
live-archive
man
merge-conflicts
mocha-test-runner
node-debugger
open-in-sourcetree
open-terminal-here
pain-split
pdf-view
pipe
regex-railroad-diagram
revert-buffer
script
sort-lines
stacktrace
svg-preview
task-list
term2
test-jumper
test-status
todo-show
trailing-spaces
turbo-javascript
vim-mode
EOF
)
