#!/bin/bash
# An installable list of the Atom IDE plugins that I use.
# To get "apm" tool: open Atom and click "Atom->Install Shell Commands"
apm install $(cat<<-EOF
Sublime-Style-Column-Selection
atom-beautify
atom-html-preview
atom-import-js
atom-ternjs
atom-typescript
autocomplete-emojis
autocomplete-json
autocomplete-modules
autocomplete-python
busy-signal
color-picker
copy-as-rtf
declarations
docblockr
editorconfig
file-icons
filesize
git-blame
git-difftool
go-plus
highlight-selected
hyperclick
intentions
language-apache
language-diff
language-nginx
language-plantuml
language-protobuf
language-svg
language-viml
linter
linter-clang
linter-cpplint
linter-csslint
linter-eslint
linter-javac
linter-js-yaml
linter-less
linter-perl
linter-pycodestyle
linter-sass-lint
linter-shellcheck
linter-stylelint
linter-tslint
linter-write-good
linter-xmllint
man
merge-conflicts
open-in-sourcetree
open-terminal-here
pdf-view
pigments
pipe
plantuml-viewer
script
sort-lines
svg-preview
term3
trailing-spaces
turbo-javascript
vim-mode-plus
EOF
)

